//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webex_Launcher_Auto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int attesa {
            get {
                return ((int)(this["attesa"]));
            }
            set {
                this["attesa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materia Non Impostata")]
        public string materia_1 {
            get {
                return ((string)(this["materia_1"]));
            }
            set {
                this["materia_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materia Non Impostata")]
        public string materia_2 {
            get {
                return ((string)(this["materia_2"]));
            }
            set {
                this["materia_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materia Non Impostata")]
        public string materia_3 {
            get {
                return ((string)(this["materia_3"]));
            }
            set {
                this["materia_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materia Non Impostata")]
        public string materia_4 {
            get {
                return ((string)(this["materia_4"]));
            }
            set {
                this["materia_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_1_1_nome {
            get {
                return ((string)(this["prof_1_1_nome"]));
            }
            set {
                this["prof_1_1_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_1_1_cognome {
            get {
                return ((string)(this["prof_1_1_cognome"]));
            }
            set {
                this["prof_1_1_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_1_2_nome {
            get {
                return ((string)(this["prof_1_2_nome"]));
            }
            set {
                this["prof_1_2_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_1_2_cognome {
            get {
                return ((string)(this["prof_1_2_cognome"]));
            }
            set {
                this["prof_1_2_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_1_3_nome {
            get {
                return ((string)(this["prof_1_3_nome"]));
            }
            set {
                this["prof_1_3_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_1_3_cognome {
            get {
                return ((string)(this["prof_1_3_cognome"]));
            }
            set {
                this["prof_1_3_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_1_4_nome {
            get {
                return ((string)(this["prof_1_4_nome"]));
            }
            set {
                this["prof_1_4_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_1_4_cognome {
            get {
                return ((string)(this["prof_1_4_cognome"]));
            }
            set {
                this["prof_1_4_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_2_1_nome {
            get {
                return ((string)(this["prof_2_1_nome"]));
            }
            set {
                this["prof_2_1_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_2_1_cognome {
            get {
                return ((string)(this["prof_2_1_cognome"]));
            }
            set {
                this["prof_2_1_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_2_2_nome {
            get {
                return ((string)(this["prof_2_2_nome"]));
            }
            set {
                this["prof_2_2_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_2_2_cognome {
            get {
                return ((string)(this["prof_2_2_cognome"]));
            }
            set {
                this["prof_2_2_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_2_3_nome {
            get {
                return ((string)(this["prof_2_3_nome"]));
            }
            set {
                this["prof_2_3_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_2_3_cognome {
            get {
                return ((string)(this["prof_2_3_cognome"]));
            }
            set {
                this["prof_2_3_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_2_4_nome {
            get {
                return ((string)(this["prof_2_4_nome"]));
            }
            set {
                this["prof_2_4_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_2_4_cognome {
            get {
                return ((string)(this["prof_2_4_cognome"]));
            }
            set {
                this["prof_2_4_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_3_1_nome {
            get {
                return ((string)(this["prof_3_1_nome"]));
            }
            set {
                this["prof_3_1_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_3_1_cognome {
            get {
                return ((string)(this["prof_3_1_cognome"]));
            }
            set {
                this["prof_3_1_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_3_2_nome {
            get {
                return ((string)(this["prof_3_2_nome"]));
            }
            set {
                this["prof_3_2_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_3_2_cognome {
            get {
                return ((string)(this["prof_3_2_cognome"]));
            }
            set {
                this["prof_3_2_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_3_3_nome {
            get {
                return ((string)(this["prof_3_3_nome"]));
            }
            set {
                this["prof_3_3_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_3_3_cognome {
            get {
                return ((string)(this["prof_3_3_cognome"]));
            }
            set {
                this["prof_3_3_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_3_4_nome {
            get {
                return ((string)(this["prof_3_4_nome"]));
            }
            set {
                this["prof_3_4_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_3_4_cognome {
            get {
                return ((string)(this["prof_3_4_cognome"]));
            }
            set {
                this["prof_3_4_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_4_1_nome {
            get {
                return ((string)(this["prof_4_1_nome"]));
            }
            set {
                this["prof_4_1_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_4_1_cognome {
            get {
                return ((string)(this["prof_4_1_cognome"]));
            }
            set {
                this["prof_4_1_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_4_2_nome {
            get {
                return ((string)(this["prof_4_2_nome"]));
            }
            set {
                this["prof_4_2_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_4_2_cognome {
            get {
                return ((string)(this["prof_4_2_cognome"]));
            }
            set {
                this["prof_4_2_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_4_3_nome {
            get {
                return ((string)(this["prof_4_3_nome"]));
            }
            set {
                this["prof_4_3_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_4_3_cognome {
            get {
                return ((string)(this["prof_4_3_cognome"]));
            }
            set {
                this["prof_4_3_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nome Prof Non Impostato")]
        public string prof_4_4_nome {
            get {
                return ((string)(this["prof_4_4_nome"]));
            }
            set {
                this["prof_4_4_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prof_4_4_cognome {
            get {
                return ((string)(this["prof_4_4_cognome"]));
            }
            set {
                this["prof_4_4_cognome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto {
            get {
                return ((bool)(this["auto"]));
            }
            set {
                this["auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string browser {
            get {
                return ((string)(this["browser"]));
            }
            set {
                this["browser"] = value;
            }
        }
    }
}
